services:
  - type: web
    name: college-merit-analyser
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar webapp-runner.jar target/college_merit_analyser.war
    envVars:
      - key: DB_HOST
        value: ""
      - key: DB_PORT
        value: ""
      - key: DB_NAME
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
